//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once


// VaDebuggerPluginServiceContract is an abstract class which defines the contract (set
// of interfaces which should be implemented) for VaDebuggerPluginService.
// VaDebuggerPluginService should inherit from this class. The properties of this class
// come from 'VaDebuggerPluginV2.vsdconfigxml'.
class DECLSPEC_NOVTABLE VaDebuggerPluginServiceContract :
    public ::Microsoft::VisualStudio::Debugger::ComponentInterfaces::IDkmLanguageStepIntoFilterCallback
{
public:
    typedef VaDebuggerPluginServiceContract Contract;
    static const CLSID ClassId;

// IUnknown methods
public:
    virtual HRESULT STDMETHODCALLTYPE QueryInterface(
        REFIID riid,
        __RPC__deref_out void __RPC_FAR *__RPC_FAR *ppvObject
        )
    {
        return _InternalQueryInterface(riid, ppvObject);
    }
    // AddRef and Release are left abstract.
    virtual ULONG STDMETHODCALLTYPE AddRef(void) = 0;
    virtual ULONG STDMETHODCALLTYPE Release(void) = 0;

protected:
    HRESULT STDMETHODCALLTYPE _InternalQueryInterface(
        REFIID riid,
        __RPC__deref_out void __RPC_FAR *__RPC_FAR *ppvObject
        )
    {
        if (ppvObject == NULL)
            return E_POINTER;

        static const IID ImplementedInterfaces[] =
        {
            { 0xa70278a3, 0xf362, 0x6f0, { 0x2b, 0xf6, 0xa4, 0xa5, 0x78, 0x60, 0xcf, 0xd3 } } // IDkmLanguageStepIntoFilterCallback
        };

        int index = FindImplementedInterface(riid, ImplementedInterfaces, sizeof(ImplementedInterfaces)/sizeof(IID));
        if (index >= 0)
        {
            *ppvObject = reinterpret_cast<size_t*>(this)+index;
            AddRef();
            return S_OK;
        }

        *ppvObject = NULL;
        return E_NOINTERFACE;
    }

private:
    // Returns the index within an array of IIDs (GUIDs) for the input search key.
    // -1 is returned if the key is not found.
    static int FindImplementedInterface(
        REFIID key, 
        _In_count_(interfaceCount) const IID implementedInterfaces[],
        int interfaceCount
        )
    {
        if (InlineIsEqualGUID(key, __uuidof(IUnknown)))
            return 0;

        for (int c = 0; c < interfaceCount; c++)
        {
            if (InlineIsEqualGUID(key, implementedInterfaces[c]))
                return c;
        }

        return -1;
    }
};
__declspec(selectany) const CLSID VaDebuggerPluginServiceContract::ClassId =
{ 0x38e80c2f, 0x90b8, 0x4cb8, { 0x97, 0x56, 0x5f, 0x34, 0x4e, 0xf1, 0x35, 0xf4 } };
