

const char *VSNetIconDefs[] = {
////<three rectanges - yellow, red, blue>",
"Class",
"Class, Internal",
"Class,",  //?<light blue diamond>
"Class, Protected",
"Class, Private",
"Class, Link",

////<white/gray rectangle containing two black lines>",
"Const",
"Const, Internal",
"Const", // ? //<light blue diamond>",
"Const, Protected",
"Const, Private",
"Const, Link",

//<briefcase with red, 3-d rectangle>",
"Breifcase",
"Breifcase, Internal",
"Breifcase", // ?, ?",
"Breifcase, Protected",
"Breifcase, Private",
"Breifcase, Link",

//<two yellow rectangles, each with two black lines>",
"Enum",
"Enum, Internal",
"Enum", // ?, ?",
"Enum, Protected",
"Enum, Private",
"Enum, Link",

//<cassette tape with yellow rectangle in background>",
"Enum item",
"Enum item, Internal",
"Enum item", // , ?",
"Enum item, Protected",
"Enum item, Private",
"Enum item, Link",

//<lightening bolt>",
"Event",
"Event, Internal",
"Event", // , ?",
"Event, Protected",
"Event, Private",
"Event, Link",

//<white square with three black lines>",
"Page",
"Page, Internal",
"Page", // , ?",
"Page, Protected",
"Page, Private",
"Page, Link",

//<light blue, 3-d rectangle>",
"Field or variable",
"Field or variable, Internal",
"Field or variable", // , ?",
"Field or variable, Protected",
"Field or variable, Private",
"Field or variable, Link",

//<magnifying glass on its side>",
"Interface",
"Interface, Internal",
"Interface", // , ?",
"Interface, Protected",
"Interface, Private",
"Interface, Link",

//<five black lines, third is a rectangle>",
"Macro",
"Macro, Internal",
"Macro", // , ?",
"Macro, Protected",
"Macro, Private",
"Macro, Link",

//<three black lines>",
"Map",
"Map, Internal",
"Map", // , ?",
"Map, Protected",
"Map, Private",
"Map, Link",

//<cassette tape with three black lines in background>",
"Map item",
"Map item, Internal",
"Map item", // , ?",
"Map item, Protected",
"Map item, Private",
"Map item, Link",

//<red, 3-d rectangle>",
"Method",
"Method, Internal",
"Method", // , ?",
"Method, Protected",
"Method, Private",
"Method, Link",

//<two red, 3-d rectangles, stacked>",
"Method",
"Method, Internal",
"Method", // , ?",
"Method, Protected",
"Method, Private",
"Method, Link",

//<five, 3-d rectangles, blurred>",
"Module",
"Module, Internal",
"Module", // , ?",
"Module, Protected",
"Module, Private",
"Module, Link",

//<braces>",
"Namespace",
"Namespace, Internal",
"Namespace", // , ?",
"Namespace, Protected",
"Namespace, Private",
"Namespace, Link",

//< (/-x+ >",
"Operator",
"Operator, Internal",
"Operator", // , ?",
"Operator, Protected",
"Operator, Private",
"Operator, Link",

//<dialog with pointing finger>",
"Property",
"Property, Internal",
"Property", // , ?",
"Property, Protected",
"Property, Private",
"Property, Link",

//<three rectanges touching - yellow, red, blue>",
"Struct",
"Struct, Internal",
"Struct", // , ?",
"Struct, Protected",
"Struct, Private",
"Struct, Link",

//<T>",
"Template",
"Template, Internal",
"Template", // , ?",
"Template, Protected",
"Template, Private",
"Template, Link",

//<white box with black trim, small white box with gray trim in background>",
"Typedef",
"Typedef, Internal",
"Typedef", // , ?",
"Typedef, Protected",
"Typedef, Private",
"Typedef, Link",

"Enum",
"Enum, Internal",
"Enum", // , ?",
"Enum, Protected",
"Enum, Private",
"Enum, Link",

//<cassette tape with yellow rectangle in background>",
"Enum item",
"Enum item, Internal",
"Enum item", // , ?",
"Enum item, Protected",
"Enum item, Private",
"Enum item, Link",

//<lightening bolt>",
"Event",
"Event, Internal",
"Event", // , ?",
"Event, Protected",
"Event, Private",
"Event, Link",

//<white square with three black lines>",
"",
"",
"", // , ?",
"",
"",
"",

//<light blue, 3-d rectangle>",
"Field or variable",
"Field or variable, Internal",
"Field or variable", // , ?",
"Field or variable, Protected",
"Field or variable, Private",
"Field or variable, Link",

//<magnifying glass on its side>",
"Interface",
"Interface, Internal",
"Interface", // , ?",
"Interface, Protected",
"Interface, Private",
"Interface, Link",

//<five black lines, third is a rectangle>",
"Macro",
"Macro, Internal",
"Macro", // , ?",
"Macro, Protected",
"Macro, Private",
"Macro, Link",

//<three black lines>",
"Map",
"Map, Internal",
"Map", // , ?",
"Map, Protected",
"Map, Private",
"Map, Link",

//<cassette tape with three black lines in background>",
"Map item",
"Map item, Internal",
"Map item", // , ?",
"Map item, Protected",
"Map item, Private",
"Map item, Link",

//<red, 3-d rectangle>",
"Method",
"Method, Internal",
"Method", // , ?",
"Method, Protected",
"Method, Private",
"Method, Link",

//<two red, 3-d rectangles, stacked>",
"",
"",
"", // , ?",
"",
"",
"",

//<five, 3-d rectangles, blurred>",
"Module",
"Module, Internal",
"Module", // , ?",
"Module, Protected",
"Module, Private",
"Module, Link",

//<braces>",
"Namespace",
"Namespace, Internal",
"Namespace", // , ?",
"Namespace, Protected",
"Namespace, Private",
"Namespace, Link",

//< (/-x+ >",
"Operator",
"Operator, Internal",
"Operator", // , ?",
"Operator, Protected",
"Operator, Private",
"Operator, Link",

//<dialog with pointing finger>",
"Property",
"Property, Internal",
"Property", // , ?",
"Property, Protected",
"Property, Private",
"Property, Link",

//<three rectanges touching - yellow, red, blue>",
"Struct",
"Struct, Internal",
"Struct", // , ?",
"Struct, Protected",
"Struct, Private",
"Struct, Link",

//<T>",
"Template",
"Template, Internal",
"Template", // , ?",
"Template, Protected",
"Template, Private",
"Template, Link",

//<white box with black trim, small white box with gray trim in background>",
"Typedef",
"Typedef, Internal",
"Typedef", // , ?",
"Typedef, Protected",
"Typedef, Private",
"Typedef, Link", NULL
};

